/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  ConflictResponse,
  CountResponse,
  GetLocationsCountParams,
  GetLocationsParams,
  GetLocationsSearchParams,
  IdResponse,
  Location,
  LocationInput,
  LocationsImportError,
  LocationsImportResult,
  NotFoundResponse,
  PayloadTooLargeResponse,
  UnauthorizedResponse
} from '../../model';

import { customInstance } from '../../mutator/customInstance';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary List locations
 */
export const getLocations = (
    params?: GetLocationsParams,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Location[]>(
    {url: `/locations`, method: 'GET',
        params
    },
    options);
  }



export const getGetLocationsKey = (params?: GetLocationsParams,) => [`/locations`, ...(params ? [params]: [])] as const;

export type GetLocationsQueryResult = NonNullable<Awaited<ReturnType<typeof getLocations>>>
export type GetLocationsQueryError = BadRequestResponse

/**
 * @summary List locations
 */
export const useGetLocations = <TError = BadRequestResponse>(
  params?: GetLocationsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getLocations>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetLocationsKey(params) : null);
  const swrFn = () => getLocations(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a location
 */
export const postLocations = (
    locationInput: LocationInput,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Location>(
    {url: `/locations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: locationInput
    },
    options);
  }



export const getPostLocationsMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: LocationInput }) => {
    return postLocations(arg, options);
  }
}
export const getPostLocationsMutationKey = () => [`/locations`] as const;

export type PostLocationsMutationResult = NonNullable<Awaited<ReturnType<typeof postLocations>>>
export type PostLocationsMutationError = BadRequestResponse | UnauthorizedResponse | ConflictResponse

/**
 * @summary Create a location
 */
export const usePostLocations = <TError = BadRequestResponse | UnauthorizedResponse | ConflictResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postLocations>>, TError, Key, LocationInput, Awaited<ReturnType<typeof postLocations>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostLocationsMutationKey();
  const swrFn = getPostLocationsMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Accepts the raw locations CSV (same columns as the seed-locations script), converts and validates each row, then upserts by case-insensitive name — updating an existing location as a full overwrite or creating a new one — and triggers a settlement-distance recompute afterwards.
 * @summary Bulk import locations from CSV (upsert by case-insensitive name; recomputes settlements)
 */
export const postLocationsImport = (
    postLocationsImportBody: Blob,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<LocationsImportResult>(
    {url: `/locations/import`, method: 'POST',
      headers: {'Content-Type': 'text/csv', },
      data: postLocationsImportBody
    },
    options);
  }



export const getPostLocationsImportMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: Blob }) => {
    return postLocationsImport(arg, options);
  }
}
export const getPostLocationsImportMutationKey = () => [`/locations/import`] as const;

export type PostLocationsImportMutationResult = NonNullable<Awaited<ReturnType<typeof postLocationsImport>>>
export type PostLocationsImportMutationError = LocationsImportError | UnauthorizedResponse | ConflictResponse | PayloadTooLargeResponse

/**
 * @summary Bulk import locations from CSV (upsert by case-insensitive name; recomputes settlements)
 */
export const usePostLocationsImport = <TError = LocationsImportError | UnauthorizedResponse | ConflictResponse | PayloadTooLargeResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postLocationsImport>>, TError, Key, Blob, Awaited<ReturnType<typeof postLocationsImport>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostLocationsImportMutationKey();
  const swrFn = getPostLocationsImportMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns every location as a CSV in the import format: fixed columns (City Name, Post code, Municipality, SAP region, Sales WB region), one column per price source, and a trailing Geo "lat,lng" column. Computed fields (settlement distances) and Mongo internals are excluded, so the output can be re-imported via POST /locations/import.
 * @summary Export all locations as CSV (same columns as the import)
 */
export const getLocationsExport = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<string>(
    {url: `/locations/export`, method: 'GET'
    },
    options);
  }



export const getGetLocationsExportKey = () => [`/locations/export`] as const;

export type GetLocationsExportQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationsExport>>>
export type GetLocationsExportQueryError = UnauthorizedResponse

/**
 * @summary Export all locations as CSV (same columns as the import)
 */
export const useGetLocationsExport = <TError = UnauthorizedResponse>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getLocationsExport>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetLocationsExportKey() : null);
  const swrFn = () => getLocationsExport(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Search locations by name
 */
export const getLocationsSearch = (
    params: GetLocationsSearchParams,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Location[]>(
    {url: `/locations/search`, method: 'GET',
        params
    },
    options);
  }



export const getGetLocationsSearchKey = (params: GetLocationsSearchParams,) => [`/locations/search`, ...(params ? [params]: [])] as const;

export type GetLocationsSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationsSearch>>>
export type GetLocationsSearchQueryError = BadRequestResponse

/**
 * @summary Search locations by name
 */
export const useGetLocationsSearch = <TError = BadRequestResponse>(
  params: GetLocationsSearchParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getLocationsSearch>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetLocationsSearchKey(params) : null);
  const swrFn = () => getLocationsSearch(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Number of locations matching the same filter as /locations/search. Omit name to count all locations.
 * @summary Count locations by name
 */
export const getLocationsCount = (
    params?: GetLocationsCountParams,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<CountResponse>(
    {url: `/locations/count`, method: 'GET',
        params
    },
    options);
  }



export const getGetLocationsCountKey = (params?: GetLocationsCountParams,) => [`/locations/count`, ...(params ? [params]: [])] as const;

export type GetLocationsCountQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationsCount>>>
export type GetLocationsCountQueryError = BadRequestResponse

/**
 * @summary Count locations by name
 */
export const useGetLocationsCount = <TError = BadRequestResponse>(
  params?: GetLocationsCountParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getLocationsCount>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetLocationsCountKey(params) : null);
  const swrFn = () => getLocationsCount(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get a location
 */
export const getLocationsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Location>(
    {url: `/locations/${id}`, method: 'GET'
    },
    options);
  }



export const getGetLocationsIdKey = (id: string,) => [`/locations/${id}`] as const;

export type GetLocationsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationsId>>>
export type GetLocationsIdQueryError = BadRequestResponse | NotFoundResponse

/**
 * @summary Get a location
 */
export const useGetLocationsId = <TError = BadRequestResponse | NotFoundResponse>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getLocationsId>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetLocationsIdKey(id) : null);
  const swrFn = () => getLocationsId(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Replace a location (full overwrite)
 */
export const patchLocationsId = (
    id: string,
    locationInput: LocationInput,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Location>(
    {url: `/locations/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: locationInput
    },
    options);
  }



export const getPatchLocationsIdMutationFetcher = (id: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: LocationInput }) => {
    return patchLocationsId(id, arg, options);
  }
}
export const getPatchLocationsIdMutationKey = (id: string,) => [`/locations/${id}`] as const;

export type PatchLocationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchLocationsId>>>
export type PatchLocationsIdMutationError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse

/**
 * @summary Replace a location (full overwrite)
 */
export const usePatchLocationsId = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof patchLocationsId>>, TError, Key, LocationInput, Awaited<ReturnType<typeof patchLocationsId>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPatchLocationsIdMutationKey(id);
  const swrFn = getPatchLocationsIdMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Delete a location
 */
export const deleteLocationsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<IdResponse>(
    {url: `/locations/${id}`, method: 'DELETE'
    },
    options);
  }



export const getDeleteLocationsIdMutationFetcher = (id: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteLocationsId(id, options);
  }
}
export const getDeleteLocationsIdMutationKey = (id: string,) => [`/locations/${id}`] as const;

export type DeleteLocationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLocationsId>>>
export type DeleteLocationsIdMutationError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse

/**
 * @summary Delete a location
 */
export const useDeleteLocationsId = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteLocationsId>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteLocationsId>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteLocationsIdMutationKey(id);
  const swrFn = getDeleteLocationsIdMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
