/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  GetConsentiApiOpenapiAdminJson200,
  GetConsentiApiOpenapiJson200,
  GetConsentiApiV1ConsentVisitorId200,
  GetConsentiApiV1ConsentVisitorIdVerify200,
  GetConsentiApiV1ProfilesAutoLocale200,
  GetConsentiApiV1ProfilesId200,
  GetConsentiApiV1ProfilesIdLocale200,
  GetConsentiApiV1ProfilesTenantIdComplianceGroupLocale200,
  GetConsentiApiV1ProfilesTenantIdProfileIdVersionLocale200,
  GetConsentiApiV1ResolveProfile200,
  GetConsentiApiV1ResolveProfileParams,
  NotFoundResponse,
  PostConsentiAdminV1AuthLogin200,
  PostConsentiAdminV1AuthLoginBody,
  PostConsentiApiV1Consent200,
  PostConsentiApiV1ConsentBody,
  PutConsentiApiV1ConsentVisitorId200,
  PutConsentiApiV1ConsentVisitorIdBody
} from '../../model';

import { customInstance } from '../../mutator/customInstance';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary Consenti public consent-capture API OpenAPI document
 */
export const getConsentiApiOpenapiJson = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<GetConsentiApiOpenapiJson200>(
    {url: `/consenti/api/openapi.json`, method: 'GET'
    },
    options);
  }



export const getGetConsentiApiOpenapiJsonKey = () => [`/consenti/api/openapi.json`] as const;

export type GetConsentiApiOpenapiJsonQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentiApiOpenapiJson>>>
export type GetConsentiApiOpenapiJsonQueryError = unknown

/**
 * @summary Consenti public consent-capture API OpenAPI document
 */
export const useGetConsentiApiOpenapiJson = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsentiApiOpenapiJson>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiApiOpenapiJsonKey() : null);
  const swrFn = () => getConsentiApiOpenapiJson(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Consenti admin API OpenAPI document
 */
export const getConsentiApiOpenapiAdminJson = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<GetConsentiApiOpenapiAdminJson200>(
    {url: `/consenti/api/openapi-admin.json`, method: 'GET'
    },
    options);
  }



export const getGetConsentiApiOpenapiAdminJsonKey = () => [`/consenti/api/openapi-admin.json`] as const;

export type GetConsentiApiOpenapiAdminJsonQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentiApiOpenapiAdminJson>>>
export type GetConsentiApiOpenapiAdminJsonQueryError = unknown

/**
 * @summary Consenti admin API OpenAPI document
 */
export const useGetConsentiApiOpenapiAdminJson = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsentiApiOpenapiAdminJson>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiApiOpenapiAdminJsonKey() : null);
  const swrFn = () => getConsentiApiOpenapiAdminJson(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Consenti Swagger UI
 */
export const getConsentiApiDocs = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<string>(
    {url: `/consenti/api/docs`, method: 'GET'
    },
    options);
  }



export const getGetConsentiApiDocsKey = () => [`/consenti/api/docs`] as const;

export type GetConsentiApiDocsQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentiApiDocs>>>
export type GetConsentiApiDocsQueryError = unknown

/**
 * @summary Consenti Swagger UI
 */
export const useGetConsentiApiDocs = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsentiApiDocs>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiApiDocsKey() : null);
  const swrFn = () => getConsentiApiDocs(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Public. Returns the profile file path + locale (for compliance.type "auto").
 * @summary Geo-resolve the compliance group for a visitor
 */
export const getConsentiApiV1ResolveProfile = (
    params: GetConsentiApiV1ResolveProfileParams,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<GetConsentiApiV1ResolveProfile200>(
    {url: `/consenti/api/v1/resolve-profile`, method: 'GET',
        params
    },
    options);
  }



export const getGetConsentiApiV1ResolveProfileKey = (params: GetConsentiApiV1ResolveProfileParams,) => [`/consenti/api/v1/resolve-profile`, ...(params ? [params]: [])] as const;

export type GetConsentiApiV1ResolveProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentiApiV1ResolveProfile>>>
export type GetConsentiApiV1ResolveProfileQueryError = BadRequestResponse

/**
 * @summary Geo-resolve the compliance group for a visitor
 */
export const useGetConsentiApiV1ResolveProfile = <TError = BadRequestResponse>(
  params: GetConsentiApiV1ResolveProfileParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsentiApiV1ResolveProfile>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiApiV1ResolveProfileKey(params) : null);
  const swrFn = () => getConsentiApiV1ResolveProfile(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Legacy: geo-resolve then return the matching active profile
 */
export const getConsentiApiV1ProfilesAutoLocale = (
    locale: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<GetConsentiApiV1ProfilesAutoLocale200>(
    {url: `/consenti/api/v1/profiles/auto/${locale}`, method: 'GET'
    },
    options);
  }



export const getGetConsentiApiV1ProfilesAutoLocaleKey = (locale: string,) => [`/consenti/api/v1/profiles/auto/${locale}`] as const;

export type GetConsentiApiV1ProfilesAutoLocaleQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentiApiV1ProfilesAutoLocale>>>
export type GetConsentiApiV1ProfilesAutoLocaleQueryError = unknown

/**
 * @summary Legacy: geo-resolve then return the matching active profile
 */
export const useGetConsentiApiV1ProfilesAutoLocale = <TError = unknown>(
  locale: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsentiApiV1ProfilesAutoLocale>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(locale)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiApiV1ProfilesAutoLocaleKey(locale) : null);
  const swrFn = () => getConsentiApiV1ProfilesAutoLocale(locale, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get a profile by id (default tenant + default locale)
 */
export const getConsentiApiV1ProfilesId = (
    id: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<GetConsentiApiV1ProfilesId200>(
    {url: `/consenti/api/v1/profiles/${id}`, method: 'GET'
    },
    options);
  }



export const getGetConsentiApiV1ProfilesIdKey = (id: string,) => [`/consenti/api/v1/profiles/${id}`] as const;

export type GetConsentiApiV1ProfilesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentiApiV1ProfilesId>>>
export type GetConsentiApiV1ProfilesIdQueryError = NotFoundResponse

/**
 * @summary Get a profile by id (default tenant + default locale)
 */
export const useGetConsentiApiV1ProfilesId = <TError = NotFoundResponse>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsentiApiV1ProfilesId>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiApiV1ProfilesIdKey(id) : null);
  const swrFn = () => getConsentiApiV1ProfilesId(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get a profile by id and locale (default tenant)
 */
export const getConsentiApiV1ProfilesIdLocale = (
    id: string,
    locale: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<GetConsentiApiV1ProfilesIdLocale200>(
    {url: `/consenti/api/v1/profiles/${id}/${locale}`, method: 'GET'
    },
    options);
  }



export const getGetConsentiApiV1ProfilesIdLocaleKey = (id: string,
    locale: string,) => [`/consenti/api/v1/profiles/${id}/${locale}`] as const;

export type GetConsentiApiV1ProfilesIdLocaleQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentiApiV1ProfilesIdLocale>>>
export type GetConsentiApiV1ProfilesIdLocaleQueryError = NotFoundResponse

/**
 * @summary Get a profile by id and locale (default tenant)
 */
export const useGetConsentiApiV1ProfilesIdLocale = <TError = NotFoundResponse>(
  id: string,
    locale: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsentiApiV1ProfilesIdLocale>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id && locale)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiApiV1ProfilesIdLocaleKey(id,locale) : null);
  const swrFn = () => getConsentiApiV1ProfilesIdLocale(id,locale, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Hot-serve a profile locale JSON straight from disk (no DB)
 */
export const getConsentiApiV1ProfilesTenantIdComplianceGroupLocale = (
    tenantId: string,
    complianceGroup: string,
    locale: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<GetConsentiApiV1ProfilesTenantIdComplianceGroupLocale200>(
    {url: `/consenti/api/v1/profiles/${tenantId}/${complianceGroup}/${locale}`, method: 'GET'
    },
    options);
  }



export const getGetConsentiApiV1ProfilesTenantIdComplianceGroupLocaleKey = (tenantId: string,
    complianceGroup: string,
    locale: string,) => [`/consenti/api/v1/profiles/${tenantId}/${complianceGroup}/${locale}`] as const;

export type GetConsentiApiV1ProfilesTenantIdComplianceGroupLocaleQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentiApiV1ProfilesTenantIdComplianceGroupLocale>>>
export type GetConsentiApiV1ProfilesTenantIdComplianceGroupLocaleQueryError = void

/**
 * @summary Hot-serve a profile locale JSON straight from disk (no DB)
 */
export const useGetConsentiApiV1ProfilesTenantIdComplianceGroupLocale = <TError = void>(
  tenantId: string,
    complianceGroup: string,
    locale: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsentiApiV1ProfilesTenantIdComplianceGroupLocale>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(tenantId && complianceGroup && locale)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiApiV1ProfilesTenantIdComplianceGroupLocaleKey(tenantId,complianceGroup,locale) : null);
  const swrFn = () => getConsentiApiV1ProfilesTenantIdComplianceGroupLocale(tenantId,complianceGroup,locale, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Serve a specific profile version locale JSON (dashboard preview)
 */
export const getConsentiApiV1ProfilesTenantIdProfileIdVersionLocale = (
    tenantId: string,
    profileId: string,
    version: string,
    locale: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<GetConsentiApiV1ProfilesTenantIdProfileIdVersionLocale200>(
    {url: `/consenti/api/v1/profiles/${tenantId}/${profileId}/${version}/${locale}`, method: 'GET'
    },
    options);
  }



export const getGetConsentiApiV1ProfilesTenantIdProfileIdVersionLocaleKey = (tenantId: string,
    profileId: string,
    version: string,
    locale: string,) => [`/consenti/api/v1/profiles/${tenantId}/${profileId}/${version}/${locale}`] as const;

export type GetConsentiApiV1ProfilesTenantIdProfileIdVersionLocaleQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentiApiV1ProfilesTenantIdProfileIdVersionLocale>>>
export type GetConsentiApiV1ProfilesTenantIdProfileIdVersionLocaleQueryError = unknown

/**
 * @summary Serve a specific profile version locale JSON (dashboard preview)
 */
export const useGetConsentiApiV1ProfilesTenantIdProfileIdVersionLocale = <TError = unknown>(
  tenantId: string,
    profileId: string,
    version: string,
    locale: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsentiApiV1ProfilesTenantIdProfileIdVersionLocale>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(tenantId && profileId && version && locale)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiApiV1ProfilesTenantIdProfileIdVersionLocaleKey(tenantId,profileId,version,locale) : null);
  const swrFn = () => getConsentiApiV1ProfilesTenantIdProfileIdVersionLocale(tenantId,profileId,version,locale, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Submit a consent record
 */
export const postConsentiApiV1Consent = (
    postConsentiApiV1ConsentBody: PostConsentiApiV1ConsentBody,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<PostConsentiApiV1Consent200>(
    {url: `/consenti/api/v1/consent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postConsentiApiV1ConsentBody
    },
    options);
  }



export const getPostConsentiApiV1ConsentMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: PostConsentiApiV1ConsentBody }) => {
    return postConsentiApiV1Consent(arg, options);
  }
}
export const getPostConsentiApiV1ConsentMutationKey = () => [`/consenti/api/v1/consent`] as const;

export type PostConsentiApiV1ConsentMutationResult = NonNullable<Awaited<ReturnType<typeof postConsentiApiV1Consent>>>
export type PostConsentiApiV1ConsentMutationError = BadRequestResponse

/**
 * @summary Submit a consent record
 */
export const usePostConsentiApiV1Consent = <TError = BadRequestResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postConsentiApiV1Consent>>, TError, Key, PostConsentiApiV1ConsentBody, Awaited<ReturnType<typeof postConsentiApiV1Consent>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostConsentiApiV1ConsentMutationKey();
  const swrFn = getPostConsentiApiV1ConsentMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get the current consent for a visitor
 */
export const getConsentiApiV1ConsentVisitorId = (
    visitorId: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<GetConsentiApiV1ConsentVisitorId200>(
    {url: `/consenti/api/v1/consent/${visitorId}`, method: 'GET'
    },
    options);
  }



export const getGetConsentiApiV1ConsentVisitorIdKey = (visitorId: string,) => [`/consenti/api/v1/consent/${visitorId}`] as const;

export type GetConsentiApiV1ConsentVisitorIdQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentiApiV1ConsentVisitorId>>>
export type GetConsentiApiV1ConsentVisitorIdQueryError = NotFoundResponse

/**
 * @summary Get the current consent for a visitor
 */
export const useGetConsentiApiV1ConsentVisitorId = <TError = NotFoundResponse>(
  visitorId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsentiApiV1ConsentVisitorId>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(visitorId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiApiV1ConsentVisitorIdKey(visitorId) : null);
  const swrFn = () => getConsentiApiV1ConsentVisitorId(visitorId, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update the consent for a visitor
 */
export const putConsentiApiV1ConsentVisitorId = (
    visitorId: string,
    putConsentiApiV1ConsentVisitorIdBody: PutConsentiApiV1ConsentVisitorIdBody,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<PutConsentiApiV1ConsentVisitorId200>(
    {url: `/consenti/api/v1/consent/${visitorId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putConsentiApiV1ConsentVisitorIdBody
    },
    options);
  }



export const getPutConsentiApiV1ConsentVisitorIdMutationFetcher = (visitorId: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: PutConsentiApiV1ConsentVisitorIdBody }) => {
    return putConsentiApiV1ConsentVisitorId(visitorId, arg, options);
  }
}
export const getPutConsentiApiV1ConsentVisitorIdMutationKey = (visitorId: string,) => [`/consenti/api/v1/consent/${visitorId}`] as const;

export type PutConsentiApiV1ConsentVisitorIdMutationResult = NonNullable<Awaited<ReturnType<typeof putConsentiApiV1ConsentVisitorId>>>
export type PutConsentiApiV1ConsentVisitorIdMutationError = BadRequestResponse | NotFoundResponse

/**
 * @summary Update the consent for a visitor
 */
export const usePutConsentiApiV1ConsentVisitorId = <TError = BadRequestResponse | NotFoundResponse>(
  visitorId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof putConsentiApiV1ConsentVisitorId>>, TError, Key, PutConsentiApiV1ConsentVisitorIdBody, Awaited<ReturnType<typeof putConsentiApiV1ConsentVisitorId>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPutConsentiApiV1ConsentVisitorIdMutationKey(visitorId);
  const swrFn = getPutConsentiApiV1ConsentVisitorIdMutationFetcher(visitorId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary GDPR right-to-erasure: delete all data for a visitor
 */
export const deleteConsentiApiV1ConsentVisitorId = (
    visitorId: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<void>(
    {url: `/consenti/api/v1/consent/${visitorId}`, method: 'DELETE'
    },
    options);
  }



export const getDeleteConsentiApiV1ConsentVisitorIdMutationFetcher = (visitorId: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteConsentiApiV1ConsentVisitorId(visitorId, options);
  }
}
export const getDeleteConsentiApiV1ConsentVisitorIdMutationKey = (visitorId: string,) => [`/consenti/api/v1/consent/${visitorId}`] as const;

export type DeleteConsentiApiV1ConsentVisitorIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteConsentiApiV1ConsentVisitorId>>>
export type DeleteConsentiApiV1ConsentVisitorIdMutationError = NotFoundResponse

/**
 * @summary GDPR right-to-erasure: delete all data for a visitor
 */
export const useDeleteConsentiApiV1ConsentVisitorId = <TError = NotFoundResponse>(
  visitorId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteConsentiApiV1ConsentVisitorId>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteConsentiApiV1ConsentVisitorId>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteConsentiApiV1ConsentVisitorIdMutationKey(visitorId);
  const swrFn = getDeleteConsentiApiV1ConsentVisitorIdMutationFetcher(visitorId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Check whether a visitor consent is still valid
 */
export const getConsentiApiV1ConsentVisitorIdVerify = (
    visitorId: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<GetConsentiApiV1ConsentVisitorIdVerify200>(
    {url: `/consenti/api/v1/consent/${visitorId}/verify`, method: 'GET'
    },
    options);
  }



export const getGetConsentiApiV1ConsentVisitorIdVerifyKey = (visitorId: string,) => [`/consenti/api/v1/consent/${visitorId}/verify`] as const;

export type GetConsentiApiV1ConsentVisitorIdVerifyQueryResult = NonNullable<Awaited<ReturnType<typeof getConsentiApiV1ConsentVisitorIdVerify>>>
export type GetConsentiApiV1ConsentVisitorIdVerifyQueryError = unknown

/**
 * @summary Check whether a visitor consent is still valid
 */
export const useGetConsentiApiV1ConsentVisitorIdVerify = <TError = unknown>(
  visitorId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsentiApiV1ConsentVisitorIdVerify>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(visitorId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiApiV1ConsentVisitorIdVerifyKey(visitorId) : null);
  const swrFn = () => getConsentiApiV1ConsentVisitorIdVerify(visitorId, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Served by consenti with its own admin auth; not gated by the app session.
 * @summary Consenti admin dashboard (single-page app)
 */
export const getConsenti = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<string>(
    {url: `/consenti`, method: 'GET'
    },
    options);
  }



export const getGetConsentiKey = () => [`/consenti`] as const;

export type GetConsentiQueryResult = NonNullable<Awaited<ReturnType<typeof getConsenti>>>
export type GetConsentiQueryError = unknown

/**
 * @summary Consenti admin dashboard (single-page app)
 */
export const useGetConsenti = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConsenti>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConsentiKey() : null);
  const swrFn = () => getConsenti(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Consenti local admin auth; not gated by the app session. The returned JWT authorizes the rest of /consenti/admin/v1/*, fully specified in GET /consenti/api/openapi-admin.json.
 * @summary Obtain a consenti admin Bearer JWT (entry point to the admin API)
 */
export const postConsentiAdminV1AuthLogin = (
    postConsentiAdminV1AuthLoginBody: PostConsentiAdminV1AuthLoginBody,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<PostConsentiAdminV1AuthLogin200>(
    {url: `/consenti/admin/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postConsentiAdminV1AuthLoginBody
    },
    options);
  }



export const getPostConsentiAdminV1AuthLoginMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: PostConsentiAdminV1AuthLoginBody }) => {
    return postConsentiAdminV1AuthLogin(arg, options);
  }
}
export const getPostConsentiAdminV1AuthLoginMutationKey = () => [`/consenti/admin/v1/auth/login`] as const;

export type PostConsentiAdminV1AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postConsentiAdminV1AuthLogin>>>
export type PostConsentiAdminV1AuthLoginMutationError = BadRequestResponse | void

/**
 * @summary Obtain a consenti admin Bearer JWT (entry point to the admin API)
 */
export const usePostConsentiAdminV1AuthLogin = <TError = BadRequestResponse | void>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postConsentiAdminV1AuthLogin>>, TError, Key, PostConsentiAdminV1AuthLoginBody, Awaited<ReturnType<typeof postConsentiAdminV1AuthLogin>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostConsentiAdminV1AuthLoginMutationKey();
  const swrFn = getPostConsentiAdminV1AuthLoginMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
