/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  Config,
  ConfigUpdate,
  UnauthorizedResponse
} from '../../model';

import { customInstance } from '../../mutator/customInstance';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary Get the configuration (created with defaults on first access)
 */
export const getConfig = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Config>(
    {url: `/config`, method: 'GET'
    },
    options);
  }



export const getGetConfigKey = () => [`/config`] as const;

export type GetConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getConfig>>>
export type GetConfigQueryError = UnauthorizedResponse

/**
 * @summary Get the configuration (created with defaults on first access)
 */
export const useGetConfig = <TError = UnauthorizedResponse>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConfig>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConfigKey() : null);
  const swrFn = () => getConfig(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update the configuration (created if absent)
 */
export const patchConfig = (
    configUpdate: ConfigUpdate,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Config>(
    {url: `/config`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: configUpdate
    },
    options);
  }



export const getPatchConfigMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: ConfigUpdate }) => {
    return patchConfig(arg, options);
  }
}
export const getPatchConfigMutationKey = () => [`/config`] as const;

export type PatchConfigMutationResult = NonNullable<Awaited<ReturnType<typeof patchConfig>>>
export type PatchConfigMutationError = BadRequestResponse | UnauthorizedResponse

/**
 * @summary Update the configuration (created if absent)
 */
export const usePatchConfig = <TError = BadRequestResponse | UnauthorizedResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof patchConfig>>, TError, Key, ConfigUpdate, Awaited<ReturnType<typeof patchConfig>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPatchConfigMutationKey();
  const swrFn = getPatchConfigMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
