/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  IdResponse,
  NotFoundResponse,
  PayloadTooLargeResponse,
  UnauthorizedResponse
} from '../../model';

import { customInstance } from '../../mutator/customInstance';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary Upload an image (raw binary body, <=50MB; compressed to WebP <=1200px)
 */
export const postImages = (
    postImagesBody: Blob,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<IdResponse>(
    {url: `/images`, method: 'POST',
      headers: {'Content-Type': 'application/octet-stream', },
      data: postImagesBody
    },
    options);
  }



export const getPostImagesMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: Blob }) => {
    return postImages(arg, options);
  }
}
export const getPostImagesMutationKey = () => [`/images`] as const;

export type PostImagesMutationResult = NonNullable<Awaited<ReturnType<typeof postImages>>>
export type PostImagesMutationError = BadRequestResponse | UnauthorizedResponse | PayloadTooLargeResponse

/**
 * @summary Upload an image (raw binary body, <=50MB; compressed to WebP <=1200px)
 */
export const usePostImages = <TError = BadRequestResponse | UnauthorizedResponse | PayloadTooLargeResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postImages>>, TError, Key, Blob, Awaited<ReturnType<typeof postImages>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostImagesMutationKey();
  const swrFn = getPostImagesMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Serve an image as WebP
 */
export const getImagesId = (
    id: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Blob>(
    {url: `/images/${id}`, method: 'GET',
        responseType: 'blob'
    },
    options);
  }



export const getGetImagesIdKey = (id: string,) => [`/images/${id}`] as const;

export type GetImagesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getImagesId>>>
export type GetImagesIdQueryError = BadRequestResponse | NotFoundResponse

/**
 * @summary Serve an image as WebP
 */
export const useGetImagesId = <TError = BadRequestResponse | NotFoundResponse>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getImagesId>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetImagesIdKey(id) : null);
  const swrFn = () => getImagesId(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
