/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  ConflictResponse,
  CountResponse,
  GetProductsCountParams,
  GetProductsIdPriceParams,
  GetProductsParams,
  GetProductsSearchParams,
  IdResponse,
  NotFoundResponse,
  PayloadTooLargeResponse,
  Product,
  ProductImportError,
  ProductImportSummary,
  ProductInput,
  ProductPricing,
  ServerErrorResponse,
  UnauthorizedResponse,
  UnprocessableEntityResponse
} from '../../model';

import { customInstance } from '../../mutator/customInstance';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary List products
 */
export const getProducts = (
    params?: GetProductsParams,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Product[]>(
    {url: `/products`, method: 'GET',
        params
    },
    options);
  }



export const getGetProductsKey = (params?: GetProductsParams,) => [`/products`, ...(params ? [params]: [])] as const;

export type GetProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getProducts>>>
export type GetProductsQueryError = BadRequestResponse

/**
 * @summary List products
 */
export const useGetProducts = <TError = BadRequestResponse>(
  params?: GetProductsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getProducts>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetProductsKey(params) : null);
  const swrFn = () => getProducts(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a product (binds the image)
 */
export const postProducts = (
    productInput: ProductInput,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Product>(
    {url: `/products`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: productInput
    },
    options);
  }



export const getPostProductsMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: ProductInput }) => {
    return postProducts(arg, options);
  }
}
export const getPostProductsMutationKey = () => [`/products`] as const;

export type PostProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postProducts>>>
export type PostProductsMutationError = BadRequestResponse | UnauthorizedResponse | ConflictResponse

/**
 * @summary Create a product (binds the image)
 */
export const usePostProducts = <TError = BadRequestResponse | UnauthorizedResponse | ConflictResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postProducts>>, TError, Key, ProductInput, Awaited<ReturnType<typeof postProducts>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostProductsMutationKey();
  const swrFn = getPostProductsMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Accepts a text/csv body. Rows are grouped by (system, variant); the mainComponent="yes" row is the product and mainComponent="no" rows are its systemComponents. Each group is matched to an existing product by sapNumber and fully overwritten, or created if none matches. All rows are validated before any write; the import runs in a single all-or-nothing transaction. Numeric columns use "." as the decimal separator; the body is UTF-8 (a leading BOM is allowed).
 * @summary Bulk import products from CSV (upsert by sapNumber)
 */
export const postProductsImport = (
    postProductsImportBody: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<ProductImportSummary>(
    {url: `/products/import`, method: 'POST',
      headers: {'Content-Type': 'text/csv', },
      data: postProductsImportBody
    },
    options);
  }



export const getPostProductsImportMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: string }) => {
    return postProductsImport(arg, options);
  }
}
export const getPostProductsImportMutationKey = () => [`/products/import`] as const;

export type PostProductsImportMutationResult = NonNullable<Awaited<ReturnType<typeof postProductsImport>>>
export type PostProductsImportMutationError = ProductImportError | UnauthorizedResponse | ConflictResponse | PayloadTooLargeResponse

/**
 * @summary Bulk import products from CSV (upsert by sapNumber)
 */
export const usePostProductsImport = <TError = ProductImportError | UnauthorizedResponse | ConflictResponse | PayloadTooLargeResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postProductsImport>>, TError, Key, string, Awaited<ReturnType<typeof postProductsImport>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostProductsImportMutationKey();
  const swrFn = getPostProductsImportMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns every product as a CSV in the import format: one mainComponent="yes" row per product followed by a mainComponent="no" row per systemComponent, sharing the parent (system, variant). Each row carries priceUnit and only its native price (rawUnitPrice for "бр.", pricePerSquareMeter for "m2"); the server-derived price of the other unit, plus unitWeightKg/weightPerSquareMeter and Mongo internals, are excluded, so the output can be re-imported via POST /products/import.
 * @summary Export all products as CSV (same columns as the import)
 */
export const getProductsExport = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<string>(
    {url: `/products/export`, method: 'GET'
    },
    options);
  }



export const getGetProductsExportKey = () => [`/products/export`] as const;

export type GetProductsExportQueryResult = NonNullable<Awaited<ReturnType<typeof getProductsExport>>>
export type GetProductsExportQueryError = UnauthorizedResponse

/**
 * @summary Export all products as CSV (same columns as the import)
 */
export const useGetProductsExport = <TError = UnauthorizedResponse>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getProductsExport>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetProductsExportKey() : null);
  const swrFn = () => getProductsExport(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Search/filter products by name, kind, and/or subtype (all optional, combined with AND)
 */
export const getProductsSearch = (
    params?: GetProductsSearchParams,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Product[]>(
    {url: `/products/search`, method: 'GET',
        params
    },
    options);
  }



export const getGetProductsSearchKey = (params?: GetProductsSearchParams,) => [`/products/search`, ...(params ? [params]: [])] as const;

export type GetProductsSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getProductsSearch>>>
export type GetProductsSearchQueryError = BadRequestResponse

/**
 * @summary Search/filter products by name, kind, and/or subtype (all optional, combined with AND)
 */
export const useGetProductsSearch = <TError = BadRequestResponse>(
  params?: GetProductsSearchParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getProductsSearch>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetProductsSearchKey(params) : null);
  const swrFn = () => getProductsSearch(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Number of products matching the same filter as /products/search.
 * @summary Count products by name, kind, and/or subtype
 */
export const getProductsCount = (
    params?: GetProductsCountParams,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<CountResponse>(
    {url: `/products/count`, method: 'GET',
        params
    },
    options);
  }



export const getGetProductsCountKey = (params?: GetProductsCountParams,) => [`/products/count`, ...(params ? [params]: [])] as const;

export type GetProductsCountQueryResult = NonNullable<Awaited<ReturnType<typeof getProductsCount>>>
export type GetProductsCountQueryError = BadRequestResponse

/**
 * @summary Count products by name, kind, and/or subtype
 */
export const useGetProductsCount = <TError = BadRequestResponse>(
  params?: GetProductsCountParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getProductsCount>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetProductsCountKey(params) : null);
  const swrFn = () => getProductsCount(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get a product
 */
export const getProductsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Product>(
    {url: `/products/${id}`, method: 'GET'
    },
    options);
  }



export const getGetProductsIdKey = (id: string,) => [`/products/${id}`] as const;

export type GetProductsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductsId>>>
export type GetProductsIdQueryError = BadRequestResponse | NotFoundResponse

/**
 * @summary Get a product
 */
export const useGetProductsId = <TError = BadRequestResponse | NotFoundResponse>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getProductsId>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetProductsIdKey(id) : null);
  const swrFn = () => getProductsId(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Replace a product (full overwrite; re-binds image if imageId changes)
 */
export const patchProductsId = (
    id: string,
    productInput: ProductInput,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Product>(
    {url: `/products/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: productInput
    },
    options);
  }



export const getPatchProductsIdMutationFetcher = (id: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: ProductInput }) => {
    return patchProductsId(id, arg, options);
  }
}
export const getPatchProductsIdMutationKey = (id: string,) => [`/products/${id}`] as const;

export type PatchProductsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchProductsId>>>
export type PatchProductsIdMutationError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse

/**
 * @summary Replace a product (full overwrite; re-binds image if imageId changes)
 */
export const usePatchProductsId = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof patchProductsId>>, TError, Key, ProductInput, Awaited<ReturnType<typeof patchProductsId>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPatchProductsIdMutationKey(id);
  const swrFn = getPatchProductsIdMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Delete a product (cascades its image)
 */
export const deleteProductsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<IdResponse>(
    {url: `/products/${id}`, method: 'DELETE'
    },
    options);
  }



export const getDeleteProductsIdMutationFetcher = (id: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteProductsId(id, options);
  }
}
export const getDeleteProductsIdMutationKey = (id: string,) => [`/products/${id}`] as const;

export type DeleteProductsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProductsId>>>
export type DeleteProductsIdMutationError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse

/**
 * @summary Delete a product (cascades its image)
 */
export const useDeleteProductsId = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteProductsId>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteProductsId>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteProductsIdMutationKey(id);
  const swrFn = getDeleteProductsIdMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Quote the delivered price of a product to a settlement
 */
export const getProductsIdPrice = (
    id: string,
    params: GetProductsIdPriceParams,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<ProductPricing>(
    {url: `/products/${id}/price`, method: 'GET',
        params
    },
    options);
  }



export const getGetProductsIdPriceKey = (id: string,
    params: GetProductsIdPriceParams,) => [`/products/${id}/price`, ...(params ? [params]: [])] as const;

export type GetProductsIdPriceQueryResult = NonNullable<Awaited<ReturnType<typeof getProductsIdPrice>>>
export type GetProductsIdPriceQueryError = BadRequestResponse | NotFoundResponse | UnprocessableEntityResponse | ServerErrorResponse

/**
 * @summary Quote the delivered price of a product to a settlement
 */
export const useGetProductsIdPrice = <TError = BadRequestResponse | NotFoundResponse | UnprocessableEntityResponse | ServerErrorResponse>(
  id: string,
    params: GetProductsIdPriceParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getProductsIdPrice>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetProductsIdPriceKey(id,params) : null);
  const swrFn = () => getProductsIdPrice(id,params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
