/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  ConflictResponse,
  NameResponse,
  NotFoundResponse,
  SourceLocation,
  SourceLocationInput,
  SourceLocationUpdate,
  UnauthorizedResponse
} from '../../model';

import { customInstance } from '../../mutator/customInstance';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary List all source locations
 */
export const getSourceLocations = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<SourceLocation[]>(
    {url: `/source-locations`, method: 'GET'
    },
    options);
  }



export const getGetSourceLocationsKey = () => [`/source-locations`] as const;

export type GetSourceLocationsQueryResult = NonNullable<Awaited<ReturnType<typeof getSourceLocations>>>
export type GetSourceLocationsQueryError = UnauthorizedResponse

/**
 * @summary List all source locations
 */
export const useGetSourceLocations = <TError = UnauthorizedResponse>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getSourceLocations>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetSourceLocationsKey() : null);
  const swrFn = () => getSourceLocations(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a source location
 */
export const postSourceLocations = (
    sourceLocationInput: SourceLocationInput,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<SourceLocation>(
    {url: `/source-locations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sourceLocationInput
    },
    options);
  }



export const getPostSourceLocationsMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: SourceLocationInput }) => {
    return postSourceLocations(arg, options);
  }
}
export const getPostSourceLocationsMutationKey = () => [`/source-locations`] as const;

export type PostSourceLocationsMutationResult = NonNullable<Awaited<ReturnType<typeof postSourceLocations>>>
export type PostSourceLocationsMutationError = BadRequestResponse | UnauthorizedResponse | ConflictResponse

/**
 * @summary Create a source location
 */
export const usePostSourceLocations = <TError = BadRequestResponse | UnauthorizedResponse | ConflictResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postSourceLocations>>, TError, Key, SourceLocationInput, Awaited<ReturnType<typeof postSourceLocations>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostSourceLocationsMutationKey();
  const swrFn = getPostSourceLocationsMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get a source location by name
 */
export const getSourceLocationsName = (
    name: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<SourceLocation>(
    {url: `/source-locations/${name}`, method: 'GET'
    },
    options);
  }



export const getGetSourceLocationsNameKey = (name: string,) => [`/source-locations/${name}`] as const;

export type GetSourceLocationsNameQueryResult = NonNullable<Awaited<ReturnType<typeof getSourceLocationsName>>>
export type GetSourceLocationsNameQueryError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse

/**
 * @summary Get a source location by name
 */
export const useGetSourceLocationsName = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse>(
  name: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getSourceLocationsName>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(name)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetSourceLocationsNameKey(name) : null);
  const swrFn = () => getSourceLocationsName(name, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update a source location truck capacity
 */
export const patchSourceLocationsName = (
    name: string,
    sourceLocationUpdate: SourceLocationUpdate,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<SourceLocation>(
    {url: `/source-locations/${name}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: sourceLocationUpdate
    },
    options);
  }



export const getPatchSourceLocationsNameMutationFetcher = (name: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: SourceLocationUpdate }) => {
    return patchSourceLocationsName(name, arg, options);
  }
}
export const getPatchSourceLocationsNameMutationKey = (name: string,) => [`/source-locations/${name}`] as const;

export type PatchSourceLocationsNameMutationResult = NonNullable<Awaited<ReturnType<typeof patchSourceLocationsName>>>
export type PatchSourceLocationsNameMutationError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse

/**
 * @summary Update a source location truck capacity
 */
export const usePatchSourceLocationsName = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse>(
  name: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof patchSourceLocationsName>>, TError, Key, SourceLocationUpdate, Awaited<ReturnType<typeof patchSourceLocationsName>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPatchSourceLocationsNameMutationKey(name);
  const swrFn = getPatchSourceLocationsNameMutationFetcher(name, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Delete a source location (blocked while referenced by a price source or a product)
 */
export const deleteSourceLocationsName = (
    name: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<NameResponse>(
    {url: `/source-locations/${name}`, method: 'DELETE'
    },
    options);
  }



export const getDeleteSourceLocationsNameMutationFetcher = (name: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteSourceLocationsName(name, options);
  }
}
export const getDeleteSourceLocationsNameMutationKey = (name: string,) => [`/source-locations/${name}`] as const;

export type DeleteSourceLocationsNameMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSourceLocationsName>>>
export type DeleteSourceLocationsNameMutationError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse

/**
 * @summary Delete a source location (blocked while referenced by a price source or a product)
 */
export const useDeleteSourceLocationsName = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse>(
  name: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteSourceLocationsName>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteSourceLocationsName>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteSourceLocationsNameMutationKey(name);
  const swrFn = getDeleteSourceLocationsNameMutationFetcher(name, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
