/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type {
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  Credentials,
  TooManyRequestsResponse,
  UnauthorizedResponse
} from '../../model';

import { customInstance } from '../../mutator/customInstance';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary Log in (creates a session cookie)
 */
export const postLogin = (
    credentials: Credentials,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<void>(
    {url: `/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: credentials
    },
    options);
  }



export const getPostLoginMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: Credentials }) => {
    return postLogin(arg, options);
  }
}
export const getPostLoginMutationKey = () => [`/login`] as const;

export type PostLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postLogin>>>
export type PostLoginMutationError = BadRequestResponse | UnauthorizedResponse | TooManyRequestsResponse

/**
 * @summary Log in (creates a session cookie)
 */
export const usePostLogin = <TError = BadRequestResponse | UnauthorizedResponse | TooManyRequestsResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postLogin>>, TError, Key, Credentials, Awaited<ReturnType<typeof postLogin>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostLoginMutationKey();
  const swrFn = getPostLoginMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
