/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  IdResponse
} from '../../model';

import { customInstance } from '../../mutator/customInstance';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary Liveness check
 */
export const getHealth = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<IdResponse>(
    {url: `/health`, method: 'GET'
    },
    options);
  }



export const getGetHealthKey = () => [`/health`] as const;

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown

/**
 * @summary Liveness check
 */
export const useGetHealth = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getHealth>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetHealthKey() : null);
  const swrFn = () => getHealth(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
