/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */

export type GetLocationsCountParams = {
/**
 * Case-insensitive substring match on name; omit to count all locations.
 * @maxLength 100
 */
name?: string;
};
