/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */

export type GetProductsParams = {
/**
 * Page number (1-based); default 1. Windows the returned array; the response shape is unchanged (a bare array).
 * @minimum 1
 */
page?: number;
/**
 * Items per page (max 100); default 20. Windows the returned array; the response shape is unchanged (a bare array).
 * @minimum 1
 * @maximum 100
 */
pageSize?: number;
};
