/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */

export type GetProductsCountParams = {
/**
 * Case-insensitive substring match on name
 * @maxLength 100
 */
name?: string;
/**
 * Exact match on product kind
 * @maxLength 100
 */
kind?: string;
/**
 * Exact match on product subtype
 * @maxLength 100
 */
subtype?: string;
};
