/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */

export type GetSettlementsCountParams = {
/**
 * Source-location name; omit to count all settlements. When set, matches the same filter as /settlements/search.
 * @maxLength 100
 */
source?: string;
};
