/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type { Point } from './point';
import type { Price } from './price';

export interface Location {
  _id?: string;
  name?: string;
  postcode?: number;
  municipality?: string;
  sapRegion?: string;
  salesWbRegion?: string;
  coordinates?: Point;
  prices?: Price[];
  createdAt?: string;
  updatedAt?: string;
}
