/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type { PointType } from './pointType';

export interface Point {
  type: PointType;
  /**
   * [longitude, latitude]
   * @minItems 2
   * @maxItems 2
   */
  coordinates: number[];
}
