/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type { ProductInputPiece } from './productInputPiece';
import type { ProductInputSquareMeter } from './productInputSquareMeter';

/**
 * PATCH is a full overwrite: absent optional fields are cleared. Changing imageId re-binds the image. Submit exactly one price: rawUnitPrice when priceUnit is "бр.", or pricePerSquareMeter when priceUnit is "m2"; the other and unitWeightKg/weightPerSquareMeter are derived server-side and cannot be set.
 */
export type ProductInput = ProductInputPiece | ProductInputSquareMeter;
