/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type { ProductInputBase } from './productInputBase';
import type { ProductInputPieceAllOf } from './productInputPieceAllOf';
import type { ProductInputPiecePriceUnit } from './productInputPiecePriceUnit';

export type ProductInputPiece = ProductInputBase & ProductInputPieceAllOf & {
  priceUnit: ProductInputPiecePriceUnit;
};
