/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type { ComponentPricing } from './componentPricing';

export interface ProductPricing {
  /** Delivered price per unit incl. fee-category markup, transport and VAT (2dp); absent when rawUnitPrice is unavailable (priceUnit "m2" without unitsPerSquareMeter) */
  pricePerUnit?: number;
  /** Delivered price per m² incl. fee-category markup, transport and VAT (2dp); absent when the item has no unitsPerSquareMeter */
  pricePerSquareMeter?: number;
  nearestLocation: string;
  distanceKm: number;
  systemComponents: ComponentPricing[];
}
