/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type { ProductPriceUnit } from './productPriceUnit';
import type { ProductProductionSource } from './productProductionSource';
import type { SystemComponent } from './systemComponent';

export interface Product {
  _id?: string;
  name?: string;
  kind?: string;
  variant?: string;
  system?: string;
  subtype?: string;
  comment?: string;
  countPerPallet?: number;
  minimumOrderUnits?: number;
  palletWeightKg?: number;
  priceUnit?: ProductPriceUnit;
  rawUnitPrice?: number;
  unitsPerSquareMeter?: number;
  unitWeightKg?: number;
  pricePerSquareMeter?: number;
  weightPerSquareMeter?: number;
  classification?: string;
  sourceLocation?: string;
  sapNumber?: string;
  feeCategory?: string;
  rasterSize?: string;
  iconLoad?: string;
  productionSource?: ProductProductionSource;
  systemComponents?: SystemComponent[];
  imageId?: string;
  createdAt?: string;
  updatedAt?: string;
}
