/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type { ProductInputBaseProductionSource } from './productInputBaseProductionSource';
import type { SystemComponentInput } from './systemComponentInput';

export interface ProductInputBase {
  /** @maxLength 100 */
  name: string;
  /** @maxLength 100 */
  kind: string;
  /** @maxLength 100 */
  variant: string;
  /** @maxLength 150 */
  system: string;
  /** @maxLength 100 */
  subtype: string;
  /** @maxLength 500 */
  comment?: string;
  /** @minimum 1 */
  countPerPallet: number;
  /** @minimum 1 */
  minimumOrderUnits: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  palletWeightKg: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  unitsPerSquareMeter?: number;
  /** @maxLength 100 */
  classification?: string;
  /**
   * Must match a source-location name
   * @maxLength 100
   */
  sourceLocation: string;
  /** @maxLength 100 */
  sapNumber: string;
  /**
   * Must match an existing fee category
   * @maxLength 100
   */
  feeCategory: string;
  /** @maxLength 100 */
  rasterSize?: string;
  /** @maxLength 100 */
  iconLoad?: string;
  productionSource: ProductInputBaseProductionSource;
  /** Optional; defaults to empty. Same per-field validation as the matching product fields. */
  systemComponents?: SystemComponentInput[];
  /** Must reference an existing, unbound image */
  imageId: string;
}
