/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type { Point } from './point';
import type { Distance } from './distance';

export interface Settlement {
  _id?: string;
  name?: string;
  coordinates?: Point;
  distances?: Distance[];
  createdAt?: string;
  updatedAt?: string;
}
