/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type { SystemComponentPriceUnit } from './systemComponentPriceUnit';

/**
 * unitWeightKg and weightPerSquareMeter are derived server-side; the price field not submitted (rawUnitPrice for "m2", pricePerSquareMeter for "бр.") is derived when unitsPerSquareMeter is present.
 */
export interface SystemComponent {
  name?: string;
  kind?: string;
  priceUnit?: SystemComponentPriceUnit;
  rawUnitPrice?: number;
  unitsPerSquareMeter?: number;
  palletWeightKg?: number;
  countPerPallet?: number;
  minimumOrderUnits?: number;
  sourceLocation?: string;
  sapNumber?: string;
  feeCategory?: string;
  unitWeightKg?: number;
  pricePerSquareMeter?: number;
  weightPerSquareMeter?: number;
}
