/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type { SystemComponentInputPiece } from './systemComponentInputPiece';
import type { SystemComponentInputSquareMeter } from './systemComponentInputSquareMeter';

/**
 * Submit exactly one price: rawUnitPrice when priceUnit is "бр.", or pricePerSquareMeter when priceUnit is "m2". The other is derived server-side when unitsPerSquareMeter is present.
 */
export type SystemComponentInput = SystemComponentInputPiece | SystemComponentInputSquareMeter;
