/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */

export interface SystemComponentInputBase {
  /** @maxLength 100 */
  name: string;
  /** @maxLength 100 */
  kind: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  unitsPerSquareMeter?: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  palletWeightKg: number;
  /** @minimum 1 */
  countPerPallet: number;
  /** @minimum 1 */
  minimumOrderUnits: number;
  /**
   * Must match a source-location name
   * @maxLength 100
   */
  sourceLocation: string;
  /** @maxLength 100 */
  sapNumber: string;
  /**
   * Must match an existing fee category
   * @maxLength 100
   */
  feeCategory: string;
}
