/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import type { SystemComponentInputBase } from './systemComponentInputBase';
import type { SystemComponentInputPieceAllOf } from './systemComponentInputPieceAllOf';
import type { SystemComponentInputPiecePriceUnit } from './systemComponentInputPiecePriceUnit';

export type SystemComponentInputPiece = SystemComponentInputBase & SystemComponentInputPieceAllOf & {
  priceUnit: SystemComponentInputPiecePriceUnit;
};
