/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  ConflictResponse,
  CountResponse,
  GetSettlementsCountParams,
  GetSettlementsParams,
  GetSettlementsSearchParams,
  IdResponse,
  NotFoundResponse,
  Settlement,
  SettlementInput,
  UnauthorizedResponse
} from '../../model';

import { customInstance } from '../../mutator/customInstance';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary List all settlements
 */
export const getSettlements = (
    params?: GetSettlementsParams,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Settlement[]>(
    {url: `/settlements`, method: 'GET',
        params
    },
    options);
  }



export const getGetSettlementsKey = (params?: GetSettlementsParams,) => [`/settlements`, ...(params ? [params]: [])] as const;

export type GetSettlementsQueryResult = NonNullable<Awaited<ReturnType<typeof getSettlements>>>
export type GetSettlementsQueryError = BadRequestResponse

/**
 * @summary List all settlements
 */
export const useGetSettlements = <TError = BadRequestResponse>(
  params?: GetSettlementsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getSettlements>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetSettlementsKey(params) : null);
  const swrFn = () => getSettlements(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a settlement (distances computed on create)
 */
export const postSettlements = (
    settlementInput: SettlementInput,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Settlement>(
    {url: `/settlements`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: settlementInput
    },
    options);
  }



export const getPostSettlementsMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: SettlementInput }) => {
    return postSettlements(arg, options);
  }
}
export const getPostSettlementsMutationKey = () => [`/settlements`] as const;

export type PostSettlementsMutationResult = NonNullable<Awaited<ReturnType<typeof postSettlements>>>
export type PostSettlementsMutationError = BadRequestResponse | UnauthorizedResponse | ConflictResponse

/**
 * @summary Create a settlement (distances computed on create)
 */
export const usePostSettlements = <TError = BadRequestResponse | UnauthorizedResponse | ConflictResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postSettlements>>, TError, Key, SettlementInput, Awaited<ReturnType<typeof postSettlements>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostSettlementsMutationKey();
  const swrFn = getPostSettlementsMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns settlements that have a distances entry whose source matches the query and is available (distanceKm != -1).
 * @summary Search settlements by available source
 */
export const getSettlementsSearch = (
    params: GetSettlementsSearchParams,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Settlement[]>(
    {url: `/settlements/search`, method: 'GET',
        params
    },
    options);
  }



export const getGetSettlementsSearchKey = (params: GetSettlementsSearchParams,) => [`/settlements/search`, ...(params ? [params]: [])] as const;

export type GetSettlementsSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getSettlementsSearch>>>
export type GetSettlementsSearchQueryError = BadRequestResponse

/**
 * @summary Search settlements by available source
 */
export const useGetSettlementsSearch = <TError = BadRequestResponse>(
  params: GetSettlementsSearchParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getSettlementsSearch>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetSettlementsSearchKey(params) : null);
  const swrFn = () => getSettlementsSearch(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Number of settlements matching the same filter as /settlements/search. Omit source to count all settlements.
 * @summary Count settlements by available source
 */
export const getSettlementsCount = (
    params?: GetSettlementsCountParams,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<CountResponse>(
    {url: `/settlements/count`, method: 'GET',
        params
    },
    options);
  }



export const getGetSettlementsCountKey = (params?: GetSettlementsCountParams,) => [`/settlements/count`, ...(params ? [params]: [])] as const;

export type GetSettlementsCountQueryResult = NonNullable<Awaited<ReturnType<typeof getSettlementsCount>>>
export type GetSettlementsCountQueryError = BadRequestResponse

/**
 * @summary Count settlements by available source
 */
export const useGetSettlementsCount = <TError = BadRequestResponse>(
  params?: GetSettlementsCountParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getSettlementsCount>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetSettlementsCountKey(params) : null);
  const swrFn = () => getSettlementsCount(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get settlements by name
 */
export const getSettlementsName = (
    name: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Settlement[]>(
    {url: `/settlements/${name}`, method: 'GET'
    },
    options);
  }



export const getGetSettlementsNameKey = (name: string,) => [`/settlements/${name}`] as const;

export type GetSettlementsNameQueryResult = NonNullable<Awaited<ReturnType<typeof getSettlementsName>>>
export type GetSettlementsNameQueryError = BadRequestResponse

/**
 * @summary Get settlements by name
 */
export const useGetSettlementsName = <TError = BadRequestResponse>(
  name: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getSettlementsName>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(name)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetSettlementsNameKey(name) : null);
  const swrFn = () => getSettlementsName(name, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Replace a settlement (full overwrite; distances recomputed)
 */
export const patchSettlementsId = (
    id: string,
    settlementInput: SettlementInput,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Settlement>(
    {url: `/settlements/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: settlementInput
    },
    options);
  }



export const getPatchSettlementsIdMutationFetcher = (id: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: SettlementInput }) => {
    return patchSettlementsId(id, arg, options);
  }
}
export const getPatchSettlementsIdMutationKey = (id: string,) => [`/settlements/${id}`] as const;

export type PatchSettlementsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchSettlementsId>>>
export type PatchSettlementsIdMutationError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse

/**
 * @summary Replace a settlement (full overwrite; distances recomputed)
 */
export const usePatchSettlementsId = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof patchSettlementsId>>, TError, Key, SettlementInput, Awaited<ReturnType<typeof patchSettlementsId>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPatchSettlementsIdMutationKey(id);
  const swrFn = getPatchSettlementsIdMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Delete a settlement
 */
export const deleteSettlementsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<IdResponse>(
    {url: `/settlements/${id}`, method: 'DELETE'
    },
    options);
  }



export const getDeleteSettlementsIdMutationFetcher = (id: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteSettlementsId(id, options);
  }
}
export const getDeleteSettlementsIdMutationKey = (id: string,) => [`/settlements/${id}`] as const;

export type DeleteSettlementsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSettlementsId>>>
export type DeleteSettlementsIdMutationError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse

/**
 * @summary Delete a settlement
 */
export const useDeleteSettlementsId = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteSettlementsId>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteSettlementsId>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteSettlementsIdMutationKey(id);
  const swrFn = getDeleteSettlementsIdMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
