/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  Account,
  BadRequestResponse,
  ConflictResponse,
  Credentials,
  ForbiddenResponse,
  IdResponse,
  NotFoundResponse,
  UnauthorizedResponse,
  UsernameResponse
} from '../../model';

import { customInstance } from '../../mutator/customInstance';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary List all accounts (password hash excluded)
 */
export const getAccounts = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Account[]>(
    {url: `/accounts`, method: 'GET'
    },
    options);
  }



export const getGetAccountsKey = () => [`/accounts`] as const;

export type GetAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof getAccounts>>>
export type GetAccountsQueryError = UnauthorizedResponse

/**
 * @summary List all accounts (password hash excluded)
 */
export const useGetAccounts = <TError = UnauthorizedResponse>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAccounts>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAccountsKey() : null);
  const swrFn = () => getAccounts(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create an account
 */
export const postAccounts = (
    credentials: Credentials,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Account>(
    {url: `/accounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: credentials
    },
    options);
  }



export const getPostAccountsMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: Credentials }) => {
    return postAccounts(arg, options);
  }
}
export const getPostAccountsMutationKey = () => [`/accounts`] as const;

export type PostAccountsMutationResult = NonNullable<Awaited<ReturnType<typeof postAccounts>>>
export type PostAccountsMutationError = BadRequestResponse | UnauthorizedResponse | ConflictResponse

/**
 * @summary Create an account
 */
export const usePostAccounts = <TError = BadRequestResponse | UnauthorizedResponse | ConflictResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postAccounts>>, TError, Key, Credentials, Awaited<ReturnType<typeof postAccounts>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostAccountsMutationKey();
  const swrFn = getPostAccountsMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get the currently authenticated account
 */
export const getAccountsMe = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<UsernameResponse>(
    {url: `/accounts/me`, method: 'GET'
    },
    options);
  }



export const getGetAccountsMeKey = () => [`/accounts/me`] as const;

export type GetAccountsMeQueryResult = NonNullable<Awaited<ReturnType<typeof getAccountsMe>>>
export type GetAccountsMeQueryError = UnauthorizedResponse

/**
 * @summary Get the currently authenticated account
 */
export const useGetAccountsMe = <TError = UnauthorizedResponse>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAccountsMe>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAccountsMeKey() : null);
  const swrFn = () => getAccountsMe(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Log out of the current session (destroys the session and clears the cookie)
 */
export const postAccountsLogout = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<void>(
    {url: `/accounts/logout`, method: 'POST'
    },
    options);
  }



export const getPostAccountsLogoutMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postAccountsLogout(options);
  }
}
export const getPostAccountsLogoutMutationKey = () => [`/accounts/logout`] as const;

export type PostAccountsLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAccountsLogout>>>
export type PostAccountsLogoutMutationError = UnauthorizedResponse

/**
 * @summary Log out of the current session (destroys the session and clears the cookie)
 */
export const usePostAccountsLogout = <TError = UnauthorizedResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postAccountsLogout>>, TError, Key, Arguments, Awaited<ReturnType<typeof postAccountsLogout>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostAccountsLogoutMutationKey();
  const swrFn = getPostAccountsLogoutMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get an account by id (password hash excluded)
 */
export const getAccountsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<Account>(
    {url: `/accounts/${id}`, method: 'GET'
    },
    options);
  }



export const getGetAccountsIdKey = (id: string,) => [`/accounts/${id}`] as const;

export type GetAccountsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAccountsId>>>
export type GetAccountsIdQueryError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse

/**
 * @summary Get an account by id (password hash excluded)
 */
export const useGetAccountsId = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAccountsId>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAccountsIdKey(id) : null);
  const swrFn = () => getAccountsId(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Delete an account (cannot delete your own or the last one)
 */
export const deleteAccountsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<IdResponse>(
    {url: `/accounts/${id}`, method: 'DELETE'
    },
    options);
  }



export const getDeleteAccountsIdMutationFetcher = (id: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteAccountsId(id, options);
  }
}
export const getDeleteAccountsIdMutationKey = (id: string,) => [`/accounts/${id}`] as const;

export type DeleteAccountsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAccountsId>>>
export type DeleteAccountsIdMutationError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse

/**
 * @summary Delete an account (cannot delete your own or the last one)
 */
export const useDeleteAccountsId = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteAccountsId>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteAccountsId>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteAccountsIdMutationKey(id);
  const swrFn = getDeleteAccountsIdMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Reset an account's failed login attempts (unlock)
 */
export const postAccountsIdResetLoginAttempts = (
    id: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<IdResponse>(
    {url: `/accounts/${id}/reset-login-attempts`, method: 'POST'
    },
    options);
  }



export const getPostAccountsIdResetLoginAttemptsMutationFetcher = (id: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postAccountsIdResetLoginAttempts(id, options);
  }
}
export const getPostAccountsIdResetLoginAttemptsMutationKey = (id: string,) => [`/accounts/${id}/reset-login-attempts`] as const;

export type PostAccountsIdResetLoginAttemptsMutationResult = NonNullable<Awaited<ReturnType<typeof postAccountsIdResetLoginAttempts>>>
export type PostAccountsIdResetLoginAttemptsMutationError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse

/**
 * @summary Reset an account's failed login attempts (unlock)
 */
export const usePostAccountsIdResetLoginAttempts = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postAccountsIdResetLoginAttempts>>, TError, Key, Arguments, Awaited<ReturnType<typeof postAccountsIdResetLoginAttempts>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostAccountsIdResetLoginAttemptsMutationKey(id);
  const swrFn = getPostAccountsIdResetLoginAttemptsMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
