/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API
 * Internal API supplying product/pricing data (bricks and construction products), transport costs and surcharges, plus dashboard configuration. Session-cookie auth; mutations and account management require authentication.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  ConflictResponse,
  FeeCategory,
  FeeCategoryInput,
  FeeCategoryUpdate,
  NameResponse,
  NotFoundResponse,
  UnauthorizedResponse
} from '../../model';

import { customInstance } from '../../mutator/customInstance';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary List all fee categories
 */
export const getFeeCategories = (
    
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<FeeCategory[]>(
    {url: `/fee-categories`, method: 'GET'
    },
    options);
  }



export const getGetFeeCategoriesKey = () => [`/fee-categories`] as const;

export type GetFeeCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getFeeCategories>>>
export type GetFeeCategoriesQueryError = UnauthorizedResponse

/**
 * @summary List all fee categories
 */
export const useGetFeeCategories = <TError = UnauthorizedResponse>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getFeeCategories>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetFeeCategoriesKey() : null);
  const swrFn = () => getFeeCategories(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a fee category
 */
export const postFeeCategories = (
    feeCategoryInput: FeeCategoryInput,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<FeeCategory>(
    {url: `/fee-categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: feeCategoryInput
    },
    options);
  }



export const getPostFeeCategoriesMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: FeeCategoryInput }) => {
    return postFeeCategories(arg, options);
  }
}
export const getPostFeeCategoriesMutationKey = () => [`/fee-categories`] as const;

export type PostFeeCategoriesMutationResult = NonNullable<Awaited<ReturnType<typeof postFeeCategories>>>
export type PostFeeCategoriesMutationError = BadRequestResponse | UnauthorizedResponse | ConflictResponse

/**
 * @summary Create a fee category
 */
export const usePostFeeCategories = <TError = BadRequestResponse | UnauthorizedResponse | ConflictResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postFeeCategories>>, TError, Key, FeeCategoryInput, Awaited<ReturnType<typeof postFeeCategories>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostFeeCategoriesMutationKey();
  const swrFn = getPostFeeCategoriesMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get a fee category by name
 */
export const getFeeCategoriesName = (
    name: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<FeeCategory>(
    {url: `/fee-categories/${name}`, method: 'GET'
    },
    options);
  }



export const getGetFeeCategoriesNameKey = (name: string,) => [`/fee-categories/${name}`] as const;

export type GetFeeCategoriesNameQueryResult = NonNullable<Awaited<ReturnType<typeof getFeeCategoriesName>>>
export type GetFeeCategoriesNameQueryError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse

/**
 * @summary Get a fee category by name
 */
export const useGetFeeCategoriesName = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse>(
  name: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getFeeCategoriesName>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(name)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetFeeCategoriesNameKey(name) : null);
  const swrFn = () => getFeeCategoriesName(name, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update a fee category percentage
 */
export const patchFeeCategoriesName = (
    name: string,
    feeCategoryUpdate: FeeCategoryUpdate,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<FeeCategory>(
    {url: `/fee-categories/${name}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: feeCategoryUpdate
    },
    options);
  }



export const getPatchFeeCategoriesNameMutationFetcher = (name: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: FeeCategoryUpdate }) => {
    return patchFeeCategoriesName(name, arg, options);
  }
}
export const getPatchFeeCategoriesNameMutationKey = (name: string,) => [`/fee-categories/${name}`] as const;

export type PatchFeeCategoriesNameMutationResult = NonNullable<Awaited<ReturnType<typeof patchFeeCategoriesName>>>
export type PatchFeeCategoriesNameMutationError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse

/**
 * @summary Update a fee category percentage
 */
export const usePatchFeeCategoriesName = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse>(
  name: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof patchFeeCategoriesName>>, TError, Key, FeeCategoryUpdate, Awaited<ReturnType<typeof patchFeeCategoriesName>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPatchFeeCategoriesNameMutationKey(name);
  const swrFn = getPatchFeeCategoriesNameMutationFetcher(name, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Delete a fee category (blocked while referenced by a product)
 */
export const deleteFeeCategoriesName = (
    name: string,
 options?: SecondParameter<typeof customInstance>) => {
    return customInstance<NameResponse>(
    {url: `/fee-categories/${name}`, method: 'DELETE'
    },
    options);
  }



export const getDeleteFeeCategoriesNameMutationFetcher = (name: string, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteFeeCategoriesName(name, options);
  }
}
export const getDeleteFeeCategoriesNameMutationKey = (name: string,) => [`/fee-categories/${name}`] as const;

export type DeleteFeeCategoriesNameMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFeeCategoriesName>>>
export type DeleteFeeCategoriesNameMutationError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse

/**
 * @summary Delete a fee category (blocked while referenced by a product)
 */
export const useDeleteFeeCategoriesName = <TError = BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse>(
  name: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteFeeCategoriesName>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteFeeCategoriesName>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteFeeCategoriesNameMutationKey(name);
  const swrFn = getDeleteFeeCategoriesNameMutationFetcher(name, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
